/*
 * Copyright (C) 2023 Daniel
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.teamdire.university_restaurant.view;

import com.teamdire.university_restaurant.controller.ControladorAutenticacao;
import com.teamdire.university_restaurant.model.UniversityRestaurant;

/**
 *
 * @author Daniel
 */
public class IUPainelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPainelPrincipal
     */
    public IUPainelPrincipal() {
        String laf = javax.swing.UIManager.getSystemLookAndFeelClassName();
        try {
            javax.swing.UIManager.setLookAndFeel(laf);
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();

        // Se o usuário não for admin, esconde as opções de admin
        if (Boolean.TRUE.equals(com.teamdire.university_restaurant.model.UniversityRestaurant.getUsuarioAutenticado().getIsAdmin()))
            return;

        // Remove todo o painel de usuários
        jMenuBar1.remove(0);
        // Remover opção de adicionar refeição
        inserirRefeicaoMenu.remove(0);
        // Remove a opção de adicionar créditos
        // Isso é ok porque esse menu (Vendas) sempre vai ter uma opção,
        // então não vai ficar feio.
        addCreditosMenuItem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        inserirRefeicaoMenu = new javax.swing.JMenu();
        inserirRefeicaoMenuItem = new javax.swing.JMenuItem();
        vendasMenu = new javax.swing.JMenu();
        addCreditosMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sairItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("Usuários");

        jMenuItem1.setText("Adicionar novo usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        inserirRefeicaoMenu.setText("Refeições");

        inserirRefeicaoMenuItem.setText("Inserir nova refeição");
        inserirRefeicaoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirRefeicaoMenuItemActionPerformed(evt);
            }
        });
        inserirRefeicaoMenu.add(inserirRefeicaoMenuItem);

        jMenuBar1.add(inserirRefeicaoMenu);

        vendasMenu.setText("Vendas");

        addCreditosMenuItem.setText("Adicionar créditos");
        addCreditosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCreditosMenuItemActionPerformed(evt);
            }
        });
        vendasMenu.add(addCreditosMenuItem);

        jMenuBar1.add(vendasMenu);

        jMenu3.setText("Sistema");

        sairItem.setLabel("Sair");
        sairItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairItemActionPerformed(evt);
            }
        });
        jMenu3.add(sairItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IUAdicionarUsuario iuAdicionarUsuario = new IUAdicionarUsuario();
        iuAdicionarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sairItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairItemActionPerformed
        ControladorAutenticacao controladorAutenticacao = new ControladorAutenticacao();
        controladorAutenticacao.deslogarUsuario();
        IUAutenticaUsuario iuAutenticaUsuario = new IUAutenticaUsuario();
        iuAutenticaUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairItemActionPerformed

    private void inserirRefeicaoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirRefeicaoMenuItemActionPerformed
        IUInserirRefeicao iuInserirRefeicao = new IUInserirRefeicao();
        iuInserirRefeicao.setVisible(true);
    }//GEN-LAST:event_inserirRefeicaoMenuItemActionPerformed

    private void addCreditosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCreditosMenuItemActionPerformed
        IUAdicionarCreditos iuAdicionarCreditos = new IUAdicionarCreditos();
        iuAdicionarCreditos.setVisible(true);
    }//GEN-LAST:event_addCreditosMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCreditosMenuItem;
    private javax.swing.JMenu inserirRefeicaoMenu;
    private javax.swing.JMenuItem inserirRefeicaoMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem sairItem;
    private javax.swing.JMenu vendasMenu;
    // End of variables declaration//GEN-END:variables
}
